In [1]:
import tensorflow as tf

In [2]:
tf.executing_eagerly()

True

In [3]:
x = [[2,]]

In [4]:
#矩阵相乘
m = tf.matmul(x, x)

In [5]:
print(m)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [6]:
m.numpy()

array([[4]])

In [7]:
a = tf.constant([[1, 2],
                 [3, 4]])

In [8]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [9]:
a.numpy()

array([[1, 2],
       [3, 4]])

In [10]:
b = tf.add(a, 1)

In [11]:
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [13]:
c = tf.multiply(a, b)

In [14]:
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [12, 20]])>

In [15]:
num = tf.convert_to_tensor(10)

In [16]:
num

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [18]:
for i in range(num.numpy()):
    i = tf.constant(i)
    if int(i%2) == 0:
        print('even')
    else:
        print('odd')

even
odd
even
odd
even
odd
even
odd
even
odd


In [19]:
import numpy as np

In [22]:
d = np.array([[5, 6],
              [7, 8]])

In [23]:
d

array([[5, 6],
       [7, 8]])

In [24]:
a + b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 5],
       [7, 9]])>

In [25]:
(a + b).numpy()

array([[3, 5],
       [7, 9]])

In [27]:
float(num)

10.0