In [2]:
import tensorflow as tf
import numpy as np

In [3]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6, 7])

In [4]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [5]:
for ele in dataset:
    print(ele.numpy())

1
2
3
4
5
6
7


In [6]:
#二维列表
dataset = tf.data.Dataset.from_tensor_slices([[1, 2], [3, 4], [5, 6]])

In [7]:
dataset

<TensorSliceDataset shapes: (2,), types: tf.int32>

In [8]:
for ele in dataset:
    print(ele.numpy())

[1 2]
[3 4]
[5 6]


In [9]:
dataset_dic = tf.data.Dataset.from_tensor_slices({'a' : [1, 2, 3, 4],
                                                  'b' : [6, 7, 8, 9],
                                                  'c' : [12, 13, 14, 15]
})

In [10]:
dataset_dic

<TensorSliceDataset shapes: {a: (), b: (), c: ()}, types: {a: tf.int32, b: tf.int32, c: tf.int32}>

In [11]:
for ele in dataset_dic:
    print(ele)

{'a': <tf.Tensor: shape=(), dtype=int32, numpy=1>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=6>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=12>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=2>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=7>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=13>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=3>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=8>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=14>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=4>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=9>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=15>}


In [13]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1, 2, 3, 4, 5, 6, 7]))

In [15]:
for ele in dataset.take(4):
    print(ele.numpy())

1
2
3
4


In [18]:
next(iter(dataset.take(1)))

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [23]:
#乱序数据集
dataset = dataset.shuffle(7)
#重复3次
dataset = dataset.repeat(count = 3)
#合并一批次，如3个数合一次
dataset = dataset.batch(3)

In [24]:
for ele in dataset:
    print(ele.numpy())

[7 2 5]
[3 1 6]
[4 7 2]
[1 2 6]
[4 5 4]
[5 1 3]
[6 7 3]
[7 3 3]
[7 2 4]
[2 4 1]
[4 6 7]
[6 5 1]
[5 2 1]
[3 6 5]
[4 6 7]
[1 3 5]
[2 2 7]
[5 5 3]
[7 3 4]
[2 4 6]
[6 1 1]


In [25]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1, 2, 3, 4, 5, 6, 7]))

In [26]:
#引用函数
dataset = dataset.map(tf.square)

In [27]:
for ele in dataset:
    print(ele.numpy())

1
4
9
16
25
36
49
